/// <reference types="vite/client" />
import { useEffect, useMemo, useRef, useState } from "react";
import type { AvatarShape, City, Page, Product, ProfileAccent, ProfileBanner, ProfileCustomization, User } from "./types";
import { addAdmin, getAdmins, getCategories, getMe, getProducts, getProfile, getSessions, logout, revokeAllSessions, revokeSession, setPassword, updateProfile, type AdminUser, type MeResponse, type SessionInfo } from "./api/api";
import "./styles/global.css";
import "./styles/profile.css";
import "./styles/marketplace.css";
import "./styles/sxron-redesign.css";

const DEFAULT_PROFILE: ProfileCustomization = { displayName: "", bio: "", status: "", avatar: "✦", accent: "cyan", banner: "aurora", avatarShape: "rounded", usernameVisible: true, badgesVisible: true, activityVisible: true };
const AVATARS = ["✦", "S", "◈", "◆", "●", "✚", "⚡", "★", "☁", "♢", "⌂", "◎", "❖", "◇", "⬢", "✧"];
const BANNERS: ProfileBanner[] = ["aurora", "violet", "ocean", "sunset"];
const SHAPES: AvatarShape[] = ["rounded", "circle", "square"];
function roleLabel(me: MeResponse | null): string { return me?.is_owner ? "Владелец" : me?.is_admin ? "Администратор" : "Пользователь"; }
function profileFromUser(user: User, me: MeResponse | null = null): ProfileCustomization { return { displayName: user.display_name || "", bio: user.bio || "", status: roleLabel(me) || user.profile_status || "Пользователь", avatar: user.avatar_url || "✦", accent: user.profile_accent || "cyan", banner: user.profile_banner || "aurora", avatarShape: user.avatar_shape || "rounded", usernameVisible: user.username_visible !== false, badgesVisible: user.badges_visible !== false, activityVisible: user.activity_visible !== false }; }
function loadProfile(): ProfileCustomization { try { return { ...DEFAULT_PROFILE, ...JSON.parse(localStorage.getItem("sxron_profile_customization") || "null") }; } catch { return DEFAULT_PROFILE; } }
function loadFavorites(): number[] { try { return JSON.parse(localStorage.getItem("sxron_favorites") || "[]"); } catch { return []; } }
function saveFavorites(ids: number[]) { try { localStorage.setItem("sxron_favorites", JSON.stringify(ids)); } catch { } }
function normalizeProduct(product: Product): Product { return { ...product, price: Number(product.price) || 0, description: product.description || "Описание отсутствует." }; }
function productCity(product: Product) { return typeof product.city === "string" ? product.city : product.city?.name || "Белореченск"; }

export default function App() {
  const [page, setPage] = useState<Page>("home");
  const [isMobile, setIsMobile] = useState(() => typeof window !== "undefined" && window.innerWidth <= 768);
  const [city] = useState<City>({ id: 1, name: "Белореченск" });
  const [profile, setProfile] = useState<ProfileCustomization>(() => loadProfile());
  const [products, setProducts] = useState<Product[]>([]);
  const [categories, setCategories] = useState<{ id: number; name: string; slug?: string; icon?: string }[]>([]);
  const [favorites, setFavorites] = useState<number[]>(() => loadFavorites());
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [sellerProduct, setSellerProduct] = useState<Product | null>(null);
  const [search, setSearch] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("Все");
  const [loading, setLoading] = useState(true);
  const [apiError, setApiError] = useState("");
  const [me, setMe] = useState<MeResponse | null>(null);
  const [admins, setAdmins] = useState<AdminUser[]>([]);
  const [adminId, setAdminId] = useState("");
  const [manageMode, setManageMode] = useState<"list" | "create" | "edit">("list");
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [toast, setToast] = useState("");
  const [profileEditorOpen, setProfileEditorOpen] = useState(false);
  const [sessions, setSessions] = useState<SessionInfo[]>([]);
  const [sessionsOpen, setSessionsOpen] = useState(false);
  const [updateAvailable, setUpdateAvailable] = useState(false);
  const [updateVersion, setUpdateVersion] = useState("");
  const [updateChecking, setUpdateChecking] = useState(false);
  const [updateMessage, setUpdateMessage] = useState("");

  useEffect(() => { const resize = () => setIsMobile(window.innerWidth <= 768); resize(); window.addEventListener("resize", resize); return () => window.removeEventListener("resize", resize); }, []);
  useEffect(() => { try { localStorage.setItem("sxron_profile_customization", JSON.stringify(profile)); } catch { } document.documentElement.dataset.sxronAccent = profile.accent; }, [profile]);
  useEffect(() => saveFavorites(favorites), [favorites]);
  useEffect(() => {
    const handler = (event: Event) => {
      const detail = (event as CustomEvent<{ event?: string; targetVersion?: string; message?: string }>).detail;
      if (!detail) return;
      if (detail.event === "checking") { setUpdateChecking(true); setUpdateMessage("Проверяем наличие новой версии…"); }
      else if (detail.event === "update-required") { setUpdateChecking(false); setUpdateAvailable(true); setUpdateVersion(detail.targetVersion || ""); setUpdateMessage(`Доступна новая версия ${detail.targetVersion || ""}.`); }
      else if (detail.event === "up-to-date") { setUpdateChecking(false); setUpdateAvailable(false); setUpdateVersion(""); setUpdateMessage("Установлена последняя версия."); }
      else if (detail.event === "download-start") { setUpdateChecking(true); setUpdateMessage(`Скачиваем версию ${detail.targetVersion || updateVersion || "новую"}…`); }
      else if (detail.event === "update-ready") { setUpdateMessage("Обновление загружено. Перезапускаем приложение…"); }
      else if (detail.event === "update-error") { setUpdateChecking(false); setUpdateMessage(detail.message || "Не удалось проверить или установить обновление."); }
    };
    window.addEventListener("sxron-updater", handler);
    return () => window.removeEventListener("sxron-updater", handler);
  }, [updateVersion]);
  useEffect(() => { let alive = true; (async () => { setLoading(true); try { const [productData, categoryData] = await Promise.all([getProducts({ city: city.name }), getCategories()]); if (!alive) return; setProducts(productData.map(normalizeProduct)); setCategories(categoryData); setApiError(""); } catch (error) { if (alive) setApiError(error instanceof Error ? error.message : "Не удалось загрузить каталог."); } finally { if (alive) setLoading(false); } })(); return () => { alive = false; }; }, [city.name]);
  useEffect(() => { getMe().then((result) => { setMe(result); setProfile((current) => ({ ...(result.user.display_name || result.user.avatar_url || result.user.bio ? profileFromUser(result.user, result) : current), status: roleLabel(result) })); }).catch(() => setMe(null)); }, []);
  useEffect(() => { if (!me?.is_admin) return; getAdmins().then((result) => setAdmins(result.admins)).catch(() => undefined); }, [me?.is_admin]);

  const filteredProducts = useMemo(() => { const query = search.trim().toLowerCase(); return products.filter((product) => { const category = product.category || "Без категории"; return (selectedCategory === "Все" || category === selectedCategory) && (!query || `${product.name} ${product.description} ${category} ${productCity(product)}`.toLowerCase().includes(query)); }); }, [products, search, selectedCategory]);
  const favoriteProducts = products.filter((product) => favorites.includes(product.id));
  const managedProducts = products.filter((product) => Boolean(product.created_by && me?.user.id === product.created_by));
  function navigate(next: Page) { setPage(next); setSelectedProduct(null); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function toggleFavorite(id: number) { setFavorites((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2600); }
  function checkForUpdates() { setUpdateChecking(true); setUpdateMessage("Проверяем наличие новой версии…"); try { window.open("sxron://check-updates"); } catch (error) { setUpdateChecking(false); setUpdateMessage(error instanceof Error ? error.message : "Не удалось запустить проверку."); } }
  function startUpdate() { setUpdateChecking(true); setUpdateMessage(`Запускаем загрузку версии ${updateVersion || "новой"}…`); try { window.open("sxron://start-update"); } catch (error) { setUpdateChecking(false); setUpdateMessage(error instanceof Error ? error.message : "Не удалось запустить обновление."); } }
  function handleLocalProductSave(product: Product) { const normalized = normalizeProduct(product); setProducts((current) => current.some((item) => item.id === normalized.id) ? current.map((item) => item.id === normalized.id ? normalized : item) : [normalized, ...current]); setEditingProduct(null); setManageMode("list"); notify("Объявление сохранено"); }
  function handleDeleteProduct(id: number) { setProducts((current) => current.filter((product) => product.id !== id)); setFavorites((current) => current.filter((item) => item !== id)); setSelectedProduct(null); notify("Объявление удалено"); }
  async function saveUserProfile(next: ProfileCustomization) { const result = await updateProfile({ display_name: next.displayName.trim(), bio: next.bio.trim(), avatar_url: next.avatar, profile_accent: next.accent, profile_banner: next.banner, avatar_shape: next.avatarShape, username_visible: next.usernameVisible, badges_visible: next.badgesVisible, activity_visible: next.activityVisible }); setProfile({ ...profileFromUser(result.user, { user: result.user, is_admin: result.is_admin, is_owner: result.is_owner }), status: roleLabel({ user: result.user, is_admin: result.is_admin, is_owner: result.is_owner }) }); setMe({ user: result.user, is_admin: result.is_admin, is_owner: result.is_owner }); setProfileEditorOpen(false); notify("Профиль обновлён"); }
  async function openSessions() { try { const result = await getSessions(); setSessions(result.sessions); setSessionsOpen(true); } catch (error) { notify(error instanceof Error ? error.message : "Не удалось загрузить сессии"); } }
  async function removeSession(id: number) { try { await revokeSession(id); setSessions((current) => current.filter((session) => session.id !== id)); notify("Сессия завершена"); } catch (error) { notify(error instanceof Error ? error.message : "Не удалось завершить сессию"); } }
  async function removeAllSessions() { try { await revokeAllSessions(); setSessions([]); notify("Другие сессии завершены"); } catch (error) { notify(error instanceof Error ? error.message : "Не удалось завершить сессии"); } }
  async function handleLogout() { await logout(); window.location.reload(); }

  const appClass = isMobile ? "sxron-shell sxron-shell--mobile" : "sxron-shell";
  return <div className={appClass}>
    <header className="sxron-topbar"><button className="sxron-brand" onClick={() => navigate("home")} aria-label="SXRON"><span className="sxron-brand__mark">S</span><span>SXRON</span></button>{!isMobile && <nav className="sxron-topnav"><button className={page === "home" ? "active" : ""} onClick={() => navigate("home")}>Главная</button><button className={page === "catalog" ? "active" : ""} onClick={() => navigate("catalog")}>Каталог</button><button className={page === "favorites" ? "active" : ""} onClick={() => navigate("favorites")}>Избранное</button><button className={page === "profile" ? "active" : ""} onClick={() => navigate("profile")} style={{ position: "relative" }}>Профиль{updateAvailable && <span style={{ position: "absolute", top: 2, right: -2, width: 7, height: 7, borderRadius: 99, background: "#20d3c2", boxShadow: "0 0 0 3px rgba(32,211,194,.12)" }} />}</button></nav>}<div className="sxron-city-pill">📍 {city.name}</div></header>
    <main className="sxron-content">
      {page === "home" && <section className="sxron-home"><div className="sxron-hero-card"><div><span className="sxron-kicker">SXRON MARKETPLACE</span><h1>Покупай.<br /><span>Продавай.</span></h1><p>Современный маркетплейс Белореченска. Найди нужное или размести своё объявление.</p><div className="sxron-actions"><button className="sxron-primary" onClick={() => navigate("catalog")}>🛍 Открыть каталог</button><button className="sxron-secondary" onClick={() => { setManageMode("create"); navigate("profile"); }}>＋ Продать</button></div></div><div className="sxron-hero-orb"><span>S</span></div></div><div className="sxron-section-head"><div><span>КАТЕГОРИИ</span><h2>Что ищем?</h2></div><button onClick={() => navigate("catalog")}>Все →</button></div><div className="sxron-category-grid">{categories.slice(0, 8).map((category) => <button key={category.id} className="sxron-category-card" onClick={() => { setSelectedCategory(category.name); navigate("catalog"); }}><strong>{category.icon || "◈"}</strong><span>{category.name}</span></button>)}</div><div className="sxron-section-head"><div><span>ПОСЛЕДНИЕ</span><h2>Новые объявления</h2></div><button onClick={() => navigate("catalog")}>Смотреть все →</button></div><ProductGrid products={products.slice(0, 6)} favorites={favorites} onFavorite={toggleFavorite} onProduct={setSelectedProduct} onSeller={setSellerProduct} /></section>}
      {page === "catalog" && <section className="sxron-page"><div className="sxron-page-head"><div><span>MARKETPLACE</span><h1>Каталог</h1><p>{filteredProducts.length} объявлений</p></div></div><div className="sxron-searchbar"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Поиск товаров и объявлений..." /><button onClick={() => { setSearch(""); setSelectedCategory("Все"); }}>Сбросить</button></div><div className="sxron-filter-scroll"><button className={selectedCategory === "Все" ? "active" : ""} onClick={() => setSelectedCategory("Все")}>Все</button>{categories.map((category) => <button key={category.id} className={selectedCategory === category.name ? "active" : ""} onClick={() => setSelectedCategory(category.name)}>{category.icon || "◈"} {category.name}</button>)}</div>{loading ? <LoadingGrid /> : apiError ? <EmptyState title="Каталог пока не подключён" text={apiError} action="Повторить" onAction={() => window.location.reload()} /> : <ProductGrid products={filteredProducts} favorites={favorites} onFavorite={toggleFavorite} onProduct={setSelectedProduct} onSeller={setSellerProduct} />}</section>}
      {page === "favorites" && <section className="sxron-page"><div className="sxron-page-head"><div><span>YOUR LIST</span><h1>Избранное</h1><p>{favoriteProducts.length} товаров</p></div></div>{favoriteProducts.length ? <ProductGrid products={favoriteProducts} favorites={favorites} onFavorite={toggleFavorite} onProduct={setSelectedProduct} onSeller={setSellerProduct} /> : <EmptyState title="Избранных товаров пока нет" text="Нажимай на сердечко на карточке товара, чтобы сохранить его здесь." action="Перейти в каталог" onAction={() => navigate("catalog")} />}</section>}
      {page === "profile" && <ProfilePage profile={profile} me={me} admins={admins} adminId={adminId} setAdminId={setAdminId} setAdmins={setAdmins} managedProducts={managedProducts} manageMode={manageMode} setManageMode={setManageMode} editingProduct={editingProduct} setEditingProduct={setEditingProduct} onProductSave={handleLocalProductSave} onDelete={handleDeleteProduct} onEdit={() => setProfileEditorOpen(true)} onSaveProfile={saveUserProfile} onOpenSessions={openSessions} onLogout={handleLogout} updateAvailable={updateAvailable} updateVersion={updateVersion} updateChecking={updateChecking} updateMessage={updateMessage} onCheckUpdates={checkForUpdates} onStartUpdate={startUpdate} />}
    </main>
    {selectedProduct && <ProductModal product={selectedProduct} favorite={favorites.includes(selectedProduct.id)} onClose={() => setSelectedProduct(null)} onFavorite={() => toggleFavorite(selectedProduct.id)} onSeller={() => setSellerProduct(selectedProduct)} />}
    {sellerProduct && <SellerModal product={sellerProduct} onClose={() => setSellerProduct(null)} />}
    {profileEditorOpen && <ProfileEditor profile={profile} onClose={() => setProfileEditorOpen(false)} onSave={saveUserProfile} />}
    {sessionsOpen && <SessionsModal sessions={sessions} onClose={() => setSessionsOpen(false)} onRevoke={removeSession} onRevokeAll={removeAllSessions} />}
    {toast && <div className="sxron-toast">{toast}</div>}
    {isMobile && <nav className="sxron-bottom-nav"><button className={page === "home" ? "active" : ""} onClick={() => navigate("home")}>⌂<span>Главная</span></button><button className={page === "catalog" ? "active" : ""} onClick={() => navigate("catalog")}>⌕<span>Каталог</span></button><button className={page === "favorites" ? "active" : ""} onClick={() => navigate("favorites")}>♡<span>Избранное</span></button><button className={page === "profile" ? "active" : ""} onClick={() => navigate("profile")}>◉<span>Профиль</span></button></nav>}
  </div>;
}

function ProductGrid({ products, favorites, onFavorite, onProduct, onSeller }: { products: Product[]; favorites: number[]; onFavorite: (id: number) => void; onProduct: (product: Product) => void; onSeller: (product: Product) => void }) {
  if (!products.length) return <EmptyState title="Ничего не найдено" text="Попробуй изменить запрос или выбрать другую категорию." action="Сбросить" onAction={() => undefined} />;
  return <div className="sxron-product-grid">{products.map((product) => <article key={product.id} className="sxron-product-card" onClick={() => onProduct(product)}><div className="sxron-product-image">{product.photo_url ? <img src={product.photo_url} alt={product.name} /> : <span>◈</span>}<button className={favorites.includes(product.id) ? "liked" : ""} onClick={(event) => { event.stopPropagation(); onFavorite(product.id); }}>{favorites.includes(product.id) ? "♥" : "♡"}</button></div><div className="sxron-product-body"><span>{product.category || "Без категории"}</span><h3>{product.name}</h3><strong>{product.price.toLocaleString("ru-RU")} ₽</strong><small>📍 {productCity(product)} · <button onClick={(event) => { event.stopPropagation(); onSeller(product); }}>продавец</button></small></div></article>)}</div>;
}

function LoadingGrid() { return <div className="sxron-product-grid">{[1, 2, 3, 4, 5, 6].map((item) => <div className="sxron-skeleton" key={item}><div /><span /><span /></div>)}</div>; }
function EmptyState({ title, text, action, onAction }: { title: string; text: string; action: string; onAction: () => void }) { return <div className="sxron-empty"><div>◈</div><h2>{title}</h2><p>{text}</p><button className="sxron-primary sxron-small" onClick={onAction}>{action}</button></div>; }

function ProductModal({ product, favorite, onClose, onFavorite, onSeller }: { product: Product; favorite: boolean; onClose: () => void; onFavorite: () => void; onSeller: () => void }) { return <div className="sxron-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="sxron-modal sxron-product-modal"><button className="sxron-modal-close" onClick={onClose}>×</button><div className="sxron-detail-image">{product.photo_url ? <img src={product.photo_url} alt={product.name} /> : <span>◈</span>}</div><div className="sxron-detail-content"><span>{product.category || "Без категории"}</span><h2>{product.name}</h2><strong className="sxron-detail-price">{product.price.toLocaleString("ru-RU")} ₽</strong><p>{product.description}</p><div className="sxron-detail-meta"><span>📍 {productCity(product)}</span><span>{product.available === false ? "Нет в наличии" : "В наличии"}</span></div><div className="sxron-detail-actions"><button className="sxron-primary" onClick={onSeller}>Связаться с продавцом</button><button className="sxron-secondary" onClick={onFavorite}>{favorite ? "♥ В избранном" : "♡ В избранное"}</button></div></div></div></div>; }
function SellerModal({ product, onClose }: { product: Product; onClose: () => void }) { return <div className="sxron-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="sxron-modal sxron-seller-modal"><button className="sxron-modal-close" onClick={onClose}>×</button><div className="sxron-seller-avatar">S</div><h2>{product.seller_name || "Продавец SXRON"}</h2><p>Продавец объявления «{product.name}». Здесь можно продолжить общение и уточнить детали покупки.</p><div className="sxron-rating">★★★★★ <b>Профиль продавца</b></div><div className="sxron-seller-stats"><div><b>{product.seller_rating ?? "—"}</b><span>рейтинг</span></div><div><b>{product.seller_sales ?? 0}</b><span>продаж</span></div><div><b>{product.seller_reviews ?? 0}</b><span>отзывов</span></div></div><button className="sxron-primary" onClick={onClose}>Закрыть</button></div></div>; }

function ProfilePage({ profile, me, admins, adminId, setAdminId, setAdmins, managedProducts, manageMode, setManageMode, editingProduct, setEditingProduct, onProductSave, onDelete, onEdit, onSaveProfile, onOpenSessions, onLogout, updateAvailable, updateVersion, updateChecking, updateMessage, onCheckUpdates, onStartUpdate }: any) {
  const role = roleLabel(me);
  return <section className="sxron-page"><div className="sxron-page-head"><div><span>ACCOUNT</span><h1>Профиль</h1><p>{role}</p></div></div><div className="sxron-profile-banner"><div className="sxron-avatar">{profile.avatar.length <= 2 ? profile.avatar : "✦"}</div><div><span>{profile.status}</span><h1>{profile.displayName || "Пользователь SXRON"}</h1><p>{profile.bio || "Добавь описание профиля, чтобы тебя было проще узнать."}</p></div><button className="sxron-secondary sxron-small" onClick={onEdit}>Настроить</button></div>{me?.is_admin && <div className="sxron-admin-card"><div className="sxron-card-head"><div><span>ADMIN</span><h2>Управление</h2></div></div><div className="sxron-admin-manage"><input value={adminId} onChange={(event) => setAdminId(event.target.value)} placeholder="Telegram ID администратора" /><button onClick={async () => { const id = Number(adminId); if (!id) return; try { const result = await addAdmin(id, "admin"); setAdmins((current: AdminUser[]) => [...current, result.admin]); setAdminId(""); } catch { } }}>Добавить</button></div><div className="sxron-admin-list">{admins.map((admin: AdminUser) => <div key={admin.user_id}><span>{admin.display_name || `ID ${admin.user_id}`}</span><b>{admin.role}</b></div>)}</div></div>}{updateMessage && <div className="sxron-admin-card"><div className="sxron-card-head"><div><span>UPDATES</span><h2>SXRON {updateVersion || "обновления"}</h2></div><button className="sxron-secondary sxron-small" onClick={updateAvailable ? onStartUpdate : onCheckUpdates}>{updateChecking ? "Проверяем…" : updateAvailable ? "Обновить" : "Проверить"}</button></div><p className="sxron-muted">{updateMessage}</p></div>}<div className="sxron-manage-card"><div className="sxron-card-head"><div><span>YOUR LISTINGS</span><h2>Мои объявления</h2></div><button className="sxron-primary sxron-small" onClick={() => setManageMode("create")}>＋ Добавить</button></div>{manageMode === "list" ? managedProducts.length ? <div className="sxron-manage-list">{managedProducts.map((product: Product) => <div className="sxron-manage-row" key={product.id}><div><strong>{product.name}</strong><span>{product.price.toLocaleString("ru-RU")} ₽</span></div><div><button onClick={() => { setEditingProduct(product); setManageMode("edit"); }}>✎</button><button onClick={() => onDelete(product.id)}>×</button></div></div>)}</div> : <p className="sxron-muted">У тебя пока нет объявлений.</p> : <ProductEditor mode={manageMode} product={editingProduct} onCancel={() => { setEditingProduct(null); setManageMode("list"); }} onSave={onProductSave} />}</div><div className="sxron-admin-card"><div className="sxron-card-head"><div><span>SECURITY</span><h2>Сессии и аккаунт</h2></div><button className="sxron-secondary sxron-small" onClick={onOpenSessions}>Сессии</button></div><button className="sxron-secondary sxron-small" onClick={onLogout}>Выйти</button></div></section>;
}

function ProfileEditor({ profile, onClose, onSave }: { profile: ProfileCustomization; onClose: () => void; onSave: (profile: ProfileCustomization) => void }) { const [value, setValue] = useState(profile); return <div className="sxron-modal-backdrop"><div className="sxron-modal sxron-seller-modal"><button className="sxron-modal-close" onClick={onClose}>×</button><span>PROFILE DESIGN</span><h2>Настройка профиля</h2><div className="sxron-editor"><input value={value.displayName} onChange={(event) => setValue({ ...value, displayName: event.target.value })} placeholder="Имя" /><textarea value={value.bio} onChange={(event) => setValue({ ...value, bio: event.target.value })} placeholder="О себе" /><div className="sxron-editor-row"><input value={value.avatar} onChange={(event) => setValue({ ...value, avatar: event.target.value })} placeholder="Аватар" /><select value={value.avatarShape} onChange={(event) => setValue({ ...value, avatarShape: event.target.value as AvatarShape })}><option value="rounded">Скругление</option><option value="circle">Круг</option><option value="square">Квадрат</option></select></div><div className="sxron-editor-actions"><button className="sxron-secondary" onClick={onClose}>Отмена</button><button className="sxron-primary" onClick={() => onSave(value)}>Сохранить</button></div></div></div></div>; }
function ProductEditor({ mode, product, onCancel, onSave }: { mode: "create" | "edit"; product: Product | null; onCancel: () => void; onSave: (product: Product) => void }) { const [value, setValue] = useState<Product>(product || { id: Date.now(), name: "", description: "", category: "", price: 0, available: true }); return <div className="sxron-editor"><input value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} placeholder="Название" /><textarea value={value.description} onChange={(event) => setValue({ ...value, description: event.target.value })} placeholder="Описание" /><div className="sxron-editor-row"><input value={value.category || ""} onChange={(event) => setValue({ ...value, category: event.target.value })} placeholder="Категория" /><input type="number" value={value.price} onChange={(event) => setValue({ ...value, price: Number(event.target.value) })} placeholder="Цена" /></div><div className="sxron-editor-actions"><button className="sxron-secondary" onClick={onCancel}>Отмена</button><button className="sxron-primary" onClick={() => onSave(value)}>{mode === "edit" ? "Сохранить" : "Создать"}</button></div></div>; }
function SessionsModal({ sessions, onClose, onRevoke, onRevokeAll }: { sessions: SessionInfo[]; onClose: () => void; onRevoke: (id: number) => void; onRevokeAll: () => void }) { return <div className="sxron-modal-backdrop"><div className="sxron-modal sxron-seller-modal"><button className="sxron-modal-close" onClick={onClose}>×</button><span>SECURITY</span><h2>Активные сессии</h2><div className="sxron-manage-list">{sessions.map((session) => <div className="sxron-manage-row" key={session.id}><div><strong>{session.user_agent || "Сессия"}</strong><span>{session.ip_address || "IP скрыт"}</span></div><button onClick={() => onRevoke(session.id)}>×</button></div>)}</div><div className="sxron-editor-actions"><button className="sxron-secondary" onClick={onRevokeAll}>Завершить другие</button><button className="sxron-primary" onClick={onClose}>Готово</button></div></div></div>; }
